/******************************************************************************
 Copyright (c) 2025  Analog Devices Inc.
******************************************************************************/

 /**
 * @file         ade9178_default.h
 * @addtogroup   ADE9178_HEADERS ADE9178 Headers
 * @brief        ADE9178 registers default values
 * @{
 */

#ifndef __ADE9178_DEFAULT_H__
#define __ADE9178_DEFAULT_H__

#define ADE9178_REG_AVGAIN_RESET                   (0x0)           /**< Default value of ADE9178_REG_AVGAIN */
#define ADE9178_REG_AVOS_RESET                     (0x0)           /**< Default value of ADE9178_REG_AVOS */
#define ADE9178_REG_AVPHCAL_RESET                  (0x0)           /**< Default value of ADE9178_REG_AVPHCAL */
#define ADE9178_REG_AVRMSOS_RESET                  (0x0)           /**< Default value of ADE9178_REG_AVRMSOS */
#define ADE9178_REG_AVRMSHALFOS_RESET              (0x0)           /**< Default value of ADE9178_REG_AVRMSHALFOS */
#define ADE9178_REG_AVRMSONEOS_RESET               (0x0)           /**< Default value of ADE9178_REG_AVRMSONEOS */
#define ADE9178_REG_AVDIPHALF_LVL_RESET            (0x0)           /**< Default value of ADE9178_REG_AVDIPHALF_LVL */
#define ADE9178_REG_AVDIPONE_LVL_RESET             (0x0)           /**< Default value of ADE9178_REG_AVDIPONE_LVL */
#define ADE9178_REG_AVSWELLHALF_LVL_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_AVSWELLHALF_LVL */
#define ADE9178_REG_AVSWELLONE_LVL_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_AVSWELLONE_LVL */
#define ADE9178_REG_AVDIPHALF_CYC_RESET            (0xffffffff)    /**< Default value of ADE9178_REG_AVDIPHALF_CYC */
#define ADE9178_REG_AVDIPONE_CYC_RESET             (0xffffffff)    /**< Default value of ADE9178_REG_AVDIPONE_CYC */
#define ADE9178_REG_AVSWELLHALF_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_AVSWELLHALF_CYC */
#define ADE9178_REG_AVSWELLONE_CYC_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_AVSWELLONE_CYC */
#define ADE9178_REG_AIGAIN_RESET                   (0x0)           /**< Default value of ADE9178_REG_AIGAIN */
#define ADE9178_REG_AIOS_RESET                     (0x0)           /**< Default value of ADE9178_REG_AIOS */
#define ADE9178_REG_AIPHCAL_RESET                  (0x0)           /**< Default value of ADE9178_REG_AIPHCAL */
#define ADE9178_REG_AIRMSOS_RESET                  (0x0)           /**< Default value of ADE9178_REG_AIRMSOS */
#define ADE9178_REG_AIRMSHALFOS_RESET              (0x0)           /**< Default value of ADE9178_REG_AIRMSHALFOS */
#define ADE9178_REG_AIRMSONEOS_RESET               (0x0)           /**< Default value of ADE9178_REG_AIRMSONEOS */
#define ADE9178_REG_AIDIPHALF_LVL_RESET            (0x0)           /**< Default value of ADE9178_REG_AIDIPHALF_LVL */
#define ADE9178_REG_AIDIPONE_LVL_RESET             (0x0)           /**< Default value of ADE9178_REG_AIDIPONE_LVL */
#define ADE9178_REG_AISWELLHALF_LVL_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_AISWELLHALF_LVL */
#define ADE9178_REG_AISWELLONE_LVL_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_AISWELLONE_LVL */
#define ADE9178_REG_AIDIPHALF_CYC_RESET            (0xffffffff)    /**< Default value of ADE9178_REG_AIDIPHALF_CYC */
#define ADE9178_REG_AIDIPONE_CYC_RESET             (0xffffffff)    /**< Default value of ADE9178_REG_AIDIPONE_CYC */
#define ADE9178_REG_AISWELLHALF_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_AISWELLHALF_CYC */
#define ADE9178_REG_AISWELLONE_CYC_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_AISWELLONE_CYC */
#define ADE9178_REG_BVGAIN_RESET                   (0x0)           /**< Default value of ADE9178_REG_BVGAIN */
#define ADE9178_REG_BVOS_RESET                     (0x0)           /**< Default value of ADE9178_REG_BVOS */
#define ADE9178_REG_BVPHCAL_RESET                  (0x0)           /**< Default value of ADE9178_REG_BVPHCAL */
#define ADE9178_REG_BVRMSOS_RESET                  (0x0)           /**< Default value of ADE9178_REG_BVRMSOS */
#define ADE9178_REG_BVRMSHALFOS_RESET              (0x0)           /**< Default value of ADE9178_REG_BVRMSHALFOS */
#define ADE9178_REG_BVRMSONEOS_RESET               (0x0)           /**< Default value of ADE9178_REG_BVRMSONEOS */
#define ADE9178_REG_BVDIPHALF_LVL_RESET            (0x0)           /**< Default value of ADE9178_REG_BVDIPHALF_LVL */
#define ADE9178_REG_BVDIPONE_LVL_RESET             (0x0)           /**< Default value of ADE9178_REG_BVDIPONE_LVL */
#define ADE9178_REG_BVSWELLHALF_LVL_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_BVSWELLHALF_LVL */
#define ADE9178_REG_BVSWELLONE_LVL_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_BVSWELLONE_LVL */
#define ADE9178_REG_BVDIPHALF_CYC_RESET            (0xffffffff)    /**< Default value of ADE9178_REG_BVDIPHALF_CYC */
#define ADE9178_REG_BVDIPONE_CYC_RESET             (0xffffffff)    /**< Default value of ADE9178_REG_BVDIPONE_CYC */
#define ADE9178_REG_BVSWELLHALF_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_BVSWELLHALF_CYC */
#define ADE9178_REG_BVSWELLONE_CYC_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_BVSWELLONE_CYC */
#define ADE9178_REG_BIGAIN_RESET                   (0x0)           /**< Default value of ADE9178_REG_BIGAIN */
#define ADE9178_REG_BIOS_RESET                     (0x0)           /**< Default value of ADE9178_REG_BIOS */
#define ADE9178_REG_BIPHCAL_RESET                  (0x0)           /**< Default value of ADE9178_REG_BIPHCAL */
#define ADE9178_REG_BIRMSOS_RESET                  (0x0)           /**< Default value of ADE9178_REG_BIRMSOS */
#define ADE9178_REG_BIRMSHALFOS_RESET              (0x0)           /**< Default value of ADE9178_REG_BIRMSHALFOS */
#define ADE9178_REG_BIRMSONEOS_RESET               (0x0)           /**< Default value of ADE9178_REG_BIRMSONEOS */
#define ADE9178_REG_BIDIPHALF_LVL_RESET            (0x0)           /**< Default value of ADE9178_REG_BIDIPHALF_LVL */
#define ADE9178_REG_BIDIPONE_LVL_RESET             (0x0)           /**< Default value of ADE9178_REG_BIDIPONE_LVL */
#define ADE9178_REG_BISWELLHALF_LVL_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_BISWELLHALF_LVL */
#define ADE9178_REG_BISWELLONE_LVL_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_BISWELLONE_LVL */
#define ADE9178_REG_BIDIPHALF_CYC_RESET            (0xffffffff)    /**< Default value of ADE9178_REG_BIDIPHALF_CYC */
#define ADE9178_REG_BIDIPONE_CYC_RESET             (0xffffffff)    /**< Default value of ADE9178_REG_BIDIPONE_CYC */
#define ADE9178_REG_BISWELLHALF_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_BISWELLHALF_CYC */
#define ADE9178_REG_BISWELLONE_CYC_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_BISWELLONE_CYC */
#define ADE9178_REG_CVGAIN_RESET                   (0x0)           /**< Default value of ADE9178_REG_CVGAIN */
#define ADE9178_REG_CVOS_RESET                     (0x0)           /**< Default value of ADE9178_REG_CVOS */
#define ADE9178_REG_CVPHCAL_RESET                  (0x0)           /**< Default value of ADE9178_REG_CVPHCAL */
#define ADE9178_REG_CVRMSOS_RESET                  (0x0)           /**< Default value of ADE9178_REG_CVRMSOS */
#define ADE9178_REG_CVRMSHALFOS_RESET              (0x0)           /**< Default value of ADE9178_REG_CVRMSHALFOS */
#define ADE9178_REG_CVRMSONEOS_RESET               (0x0)           /**< Default value of ADE9178_REG_CVRMSONEOS */
#define ADE9178_REG_CVDIPHALF_LVL_RESET            (0x0)           /**< Default value of ADE9178_REG_CVDIPHALF_LVL */
#define ADE9178_REG_CVDIPONE_LVL_RESET             (0x0)           /**< Default value of ADE9178_REG_CVDIPONE_LVL */
#define ADE9178_REG_CVSWELLHALF_LVL_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_CVSWELLHALF_LVL */
#define ADE9178_REG_CVSWELLONE_LVL_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_CVSWELLONE_LVL */
#define ADE9178_REG_CVDIPHALF_CYC_RESET            (0xffffffff)    /**< Default value of ADE9178_REG_CVDIPHALF_CYC */
#define ADE9178_REG_CVDIPONE_CYC_RESET             (0xffffffff)    /**< Default value of ADE9178_REG_CVDIPONE_CYC */
#define ADE9178_REG_CVSWELLHALF_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_CVSWELLHALF_CYC */
#define ADE9178_REG_CVSWELLONE_CYC_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_CVSWELLONE_CYC */
#define ADE9178_REG_CIGAIN_RESET                   (0x0)           /**< Default value of ADE9178_REG_CIGAIN */
#define ADE9178_REG_CIOS_RESET                     (0x0)           /**< Default value of ADE9178_REG_CIOS */
#define ADE9178_REG_CIPHCAL_RESET                  (0x0)           /**< Default value of ADE9178_REG_CIPHCAL */
#define ADE9178_REG_CIRMSOS_RESET                  (0x0)           /**< Default value of ADE9178_REG_CIRMSOS */
#define ADE9178_REG_CIRMSHALFOS_RESET              (0x0)           /**< Default value of ADE9178_REG_CIRMSHALFOS */
#define ADE9178_REG_CIRMSONEOS_RESET               (0x0)           /**< Default value of ADE9178_REG_CIRMSONEOS */
#define ADE9178_REG_CIDIPHALF_LVL_RESET            (0x0)           /**< Default value of ADE9178_REG_CIDIPHALF_LVL */
#define ADE9178_REG_CIDIPONE_LVL_RESET             (0x0)           /**< Default value of ADE9178_REG_CIDIPONE_LVL */
#define ADE9178_REG_CISWELLHALF_LVL_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_CISWELLHALF_LVL */
#define ADE9178_REG_CISWELLONE_LVL_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_CISWELLONE_LVL */
#define ADE9178_REG_CIDIPHALF_CYC_RESET            (0xffffffff)    /**< Default value of ADE9178_REG_CIDIPHALF_CYC */
#define ADE9178_REG_CIDIPONE_CYC_RESET             (0xffffffff)    /**< Default value of ADE9178_REG_CIDIPONE_CYC */
#define ADE9178_REG_CISWELLHALF_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_CISWELLHALF_CYC */
#define ADE9178_REG_CISWELLONE_CYC_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_CISWELLONE_CYC */
#define ADE9178_REG_AUX0GAIN_RESET                 (0x0)           /**< Default value of ADE9178_REG_AUX0GAIN */
#define ADE9178_REG_AUX0OS_RESET                   (0x0)           /**< Default value of ADE9178_REG_AUX0OS */
#define ADE9178_REG_AUX0PHCAL_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX0PHCAL */
#define ADE9178_REG_AUX0RMSOS_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX0RMSOS */
#define ADE9178_REG_AUX0RMSHALFOS_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX0RMSHALFOS */
#define ADE9178_REG_AUX0RMSONEOS_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX0RMSONEOS */
#define ADE9178_REG_AUX0DIPHALF_LVL_RESET          (0x0)           /**< Default value of ADE9178_REG_AUX0DIPHALF_LVL */
#define ADE9178_REG_AUX0DIPONE_LVL_RESET           (0x0)           /**< Default value of ADE9178_REG_AUX0DIPONE_LVL */
#define ADE9178_REG_AUX0SWELLHALF_LVL_RESET        (0xffffffff)    /**< Default value of ADE9178_REG_AUX0SWELLHALF_LVL */
#define ADE9178_REG_AUX0SWELLONE_LVL_RESET         (0xffffffff)    /**< Default value of ADE9178_REG_AUX0SWELLONE_LVL */
#define ADE9178_REG_AUX0DIPHALF_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_AUX0DIPHALF_CYC */
#define ADE9178_REG_AUX0DIPONE_CYC_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_AUX0DIPONE_CYC */
#define ADE9178_REG_AUX0SWELLHALF_CYC_RESET        (0xffffffff)    /**< Default value of ADE9178_REG_AUX0SWELLHALF_CYC */
#define ADE9178_REG_AUX0SWELLONE_CYC_RESET         (0xffffffff)    /**< Default value of ADE9178_REG_AUX0SWELLONE_CYC */
#define ADE9178_REG_AUX1GAIN_RESET                 (0x0)           /**< Default value of ADE9178_REG_AUX1GAIN */
#define ADE9178_REG_AUX1OS_RESET                   (0x0)           /**< Default value of ADE9178_REG_AUX1OS */
#define ADE9178_REG_AUX1PHCAL_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX1PHCAL */
#define ADE9178_REG_AUX1RMSOS_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX1RMSOS */
#define ADE9178_REG_AUX1RMSHALFOS_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX1RMSHALFOS */
#define ADE9178_REG_AUX1RMSONEOS_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX1RMSONEOS */
#define ADE9178_REG_AUX1DIPHALF_LVL_RESET          (0x0)           /**< Default value of ADE9178_REG_AUX1DIPHALF_LVL */
#define ADE9178_REG_AUX1DIPONE_LVL_RESET           (0x0)           /**< Default value of ADE9178_REG_AUX1DIPONE_LVL */
#define ADE9178_REG_AUX1SWELLHALF_LVL_RESET        (0xffffffff)    /**< Default value of ADE9178_REG_AUX1SWELLHALF_LVL */
#define ADE9178_REG_AUX1SWELLONE_LVL_RESET         (0xffffffff)    /**< Default value of ADE9178_REG_AUX1SWELLONE_LVL */
#define ADE9178_REG_AUX1DIPHALF_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_AUX1DIPHALF_CYC */
#define ADE9178_REG_AUX1DIPONE_CYC_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_AUX1DIPONE_CYC */
#define ADE9178_REG_AUX1SWELLHALF_CYC_RESET        (0xffffffff)    /**< Default value of ADE9178_REG_AUX1SWELLHALF_CYC */
#define ADE9178_REG_AUX1SWELLONE_CYC_RESET         (0xffffffff)    /**< Default value of ADE9178_REG_AUX1SWELLONE_CYC */
#define ADE9178_REG_AUX2GAIN_RESET                 (0x0)           /**< Default value of ADE9178_REG_AUX2GAIN */
#define ADE9178_REG_AUX2OS_RESET                   (0x0)           /**< Default value of ADE9178_REG_AUX2OS */
#define ADE9178_REG_AUX2PHCAL_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX2PHCAL */
#define ADE9178_REG_AUX2RMSOS_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX2RMSOS */
#define ADE9178_REG_AUX2RMSHALFOS_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX2RMSHALFOS */
#define ADE9178_REG_AUX2RMSONEOS_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX2RMSONEOS */
#define ADE9178_REG_AUX2DIPHALF_LVL_RESET          (0x0)           /**< Default value of ADE9178_REG_AUX2DIPHALF_LVL */
#define ADE9178_REG_AUX2DIPONE_LVL_RESET           (0x0)           /**< Default value of ADE9178_REG_AUX2DIPONE_LVL */
#define ADE9178_REG_AUX2SWELLHALF_LVL_RESET        (0xffffffff)    /**< Default value of ADE9178_REG_AUX2SWELLHALF_LVL */
#define ADE9178_REG_AUX2SWELLONE_LVL_RESET         (0xffffffff)    /**< Default value of ADE9178_REG_AUX2SWELLONE_LVL */
#define ADE9178_REG_AUX2DIPHALF_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_AUX2DIPHALF_CYC */
#define ADE9178_REG_AUX2DIPONE_CYC_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_AUX2DIPONE_CYC */
#define ADE9178_REG_AUX2SWELLHALF_CYC_RESET        (0xffffffff)    /**< Default value of ADE9178_REG_AUX2SWELLHALF_CYC */
#define ADE9178_REG_AUX2SWELLONE_CYC_RESET         (0xffffffff)    /**< Default value of ADE9178_REG_AUX2SWELLONE_CYC */
#define ADE9178_REG_AUX3GAIN_RESET                 (0x0)           /**< Default value of ADE9178_REG_AUX3GAIN */
#define ADE9178_REG_AUX3OS_RESET                   (0x0)           /**< Default value of ADE9178_REG_AUX3OS */
#define ADE9178_REG_AUX3PHCAL_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX3PHCAL */
#define ADE9178_REG_AUX3RMSOS_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX3RMSOS */
#define ADE9178_REG_AUX3RMSHALFOS_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX3RMSHALFOS */
#define ADE9178_REG_AUX3RMSONEOS_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX3RMSONEOS */
#define ADE9178_REG_AUX3DIPHALF_LVL_RESET          (0x0)           /**< Default value of ADE9178_REG_AUX3DIPHALF_LVL */
#define ADE9178_REG_AUX3DIPONE_LVL_RESET           (0x0)           /**< Default value of ADE9178_REG_AUX3DIPONE_LVL */
#define ADE9178_REG_AUX3SWELLHALF_LVL_RESET        (0xffffffff)    /**< Default value of ADE9178_REG_AUX3SWELLHALF_LVL */
#define ADE9178_REG_AUX3SWELLONE_LVL_RESET         (0xffffffff)    /**< Default value of ADE9178_REG_AUX3SWELLONE_LVL */
#define ADE9178_REG_AUX3DIPHALF_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_AUX3DIPHALF_CYC */
#define ADE9178_REG_AUX3DIPONE_CYC_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_AUX3DIPONE_CYC */
#define ADE9178_REG_AUX3SWELLHALF_CYC_RESET        (0xffffffff)    /**< Default value of ADE9178_REG_AUX3SWELLHALF_CYC */
#define ADE9178_REG_AUX3SWELLONE_CYC_RESET         (0xffffffff)    /**< Default value of ADE9178_REG_AUX3SWELLONE_CYC */
#define ADE9178_REG_AUX4GAIN_RESET                 (0x0)           /**< Default value of ADE9178_REG_AUX4GAIN */
#define ADE9178_REG_AUX4OS_RESET                   (0x0)           /**< Default value of ADE9178_REG_AUX4OS */
#define ADE9178_REG_AUX4PHCAL_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX4PHCAL */
#define ADE9178_REG_AUX4RMSOS_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX4RMSOS */
#define ADE9178_REG_AUX4RMSHALFOS_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX4RMSHALFOS */
#define ADE9178_REG_AUX4RMSONEOS_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX4RMSONEOS */
#define ADE9178_REG_AUX4DIPHALF_LVL_RESET          (0x0)           /**< Default value of ADE9178_REG_AUX4DIPHALF_LVL */
#define ADE9178_REG_AUX4DIPONE_LVL_RESET           (0x0)           /**< Default value of ADE9178_REG_AUX4DIPONE_LVL */
#define ADE9178_REG_AUX4SWELLHALF_LVL_RESET        (0xffffffff)    /**< Default value of ADE9178_REG_AUX4SWELLHALF_LVL */
#define ADE9178_REG_AUX4SWELLONE_LVL_RESET         (0xffffffff)    /**< Default value of ADE9178_REG_AUX4SWELLONE_LVL */
#define ADE9178_REG_AUX4DIPHALF_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_AUX4DIPHALF_CYC */
#define ADE9178_REG_AUX4DIPONE_CYC_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_AUX4DIPONE_CYC */
#define ADE9178_REG_AUX4SWELLHALF_CYC_RESET        (0xffffffff)    /**< Default value of ADE9178_REG_AUX4SWELLHALF_CYC */
#define ADE9178_REG_AUX4SWELLONE_CYC_RESET         (0xffffffff)    /**< Default value of ADE9178_REG_AUX4SWELLONE_CYC */
#define ADE9178_REG_AUX5GAIN_RESET                 (0x0)           /**< Default value of ADE9178_REG_AUX5GAIN */
#define ADE9178_REG_AUX5OS_RESET                   (0x0)           /**< Default value of ADE9178_REG_AUX5OS */
#define ADE9178_REG_AUX5PHCAL_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX5PHCAL */
#define ADE9178_REG_AUX5RMSOS_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX5RMSOS */
#define ADE9178_REG_AUX5RMSHALFOS_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX5RMSHALFOS */
#define ADE9178_REG_AUX5RMSONEOS_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX5RMSONEOS */
#define ADE9178_REG_AUX5DIPHALF_LVL_RESET          (0x0)           /**< Default value of ADE9178_REG_AUX5DIPHALF_LVL */
#define ADE9178_REG_AUX5DIPONE_LVL_RESET           (0x0)           /**< Default value of ADE9178_REG_AUX5DIPONE_LVL */
#define ADE9178_REG_AUX5SWELLHALF_LVL_RESET        (0xffffffff)    /**< Default value of ADE9178_REG_AUX5SWELLHALF_LVL */
#define ADE9178_REG_AUX5SWELLONE_LVL_RESET         (0xffffffff)    /**< Default value of ADE9178_REG_AUX5SWELLONE_LVL */
#define ADE9178_REG_AUX5DIPHALF_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_AUX5DIPHALF_CYC */
#define ADE9178_REG_AUX5DIPONE_CYC_RESET           (0xffffffff)    /**< Default value of ADE9178_REG_AUX5DIPONE_CYC */
#define ADE9178_REG_AUX5SWELLHALF_CYC_RESET        (0xffffffff)    /**< Default value of ADE9178_REG_AUX5SWELLHALF_CYC */
#define ADE9178_REG_AUX5SWELLONE_CYC_RESET         (0xffffffff)    /**< Default value of ADE9178_REG_AUX5SWELLONE_CYC */
#define ADE9178_REG_APGAIN_RESET                   (0x0)           /**< Default value of ADE9178_REG_APGAIN */
#define ADE9178_REG_AWATTOS_RESET                  (0x0)           /**< Default value of ADE9178_REG_AWATTOS */
#define ADE9178_REG_BPGAIN_RESET                   (0x0)           /**< Default value of ADE9178_REG_BPGAIN */
#define ADE9178_REG_BWATTOS_RESET                  (0x0)           /**< Default value of ADE9178_REG_BWATTOS */
#define ADE9178_REG_CPGAIN_RESET                   (0x0)           /**< Default value of ADE9178_REG_CPGAIN */
#define ADE9178_REG_CWATTOS_RESET                  (0x0)           /**< Default value of ADE9178_REG_CWATTOS */
#define ADE9178_REG_CONFIG0_RESET                  (0xd80)         /**< Default value of ADE9178_REG_CONFIG0 */
#define ADE9178_REG_PEAK_CONFIG_RESET              (0x0)           /**< Default value of ADE9178_REG_PEAK_CONFIG */
#define ADE9178_REG_PEN_CONFIG_RESET               (0x3420)        /**< Default value of ADE9178_REG_PEN_CONFIG */
#define ADE9178_REG_CF1_CONFIG_RESET               (0x1)           /**< Default value of ADE9178_REG_CF1_CONFIG */
#define ADE9178_REG_CF2_CONFIG_RESET               (0x1)           /**< Default value of ADE9178_REG_CF2_CONFIG */
#define ADE9178_REG_ISUMRMSOS_RESET                (0x0)           /**< Default value of ADE9178_REG_ISUMRMSOS */
#define ADE9178_REG_ISUMLVL_RESET                  (0x0)           /**< Default value of ADE9178_REG_ISUMLVL */
#define ADE9178_REG_VNOM_RESET                     (0x0)           /**< Default value of ADE9178_REG_VNOM */
#define ADE9178_REG_USER_PERIOD_RESET              (0x500000)      /**< Default value of ADE9178_REG_USER_PERIOD */
#define ADE9178_REG_RMSHALF_CONFIG_RESET           (0x0)           /**< Default value of ADE9178_REG_RMSHALF_CONFIG */
#define ADE9178_REG_USER_PERIOD_HALF_RESET         (0x280000)      /**< Default value of ADE9178_REG_USER_PERIOD_HALF */
#define ADE9178_REG_CF1_THR_RESET                  (0xffff)        /**< Default value of ADE9178_REG_CF1_THR */
#define ADE9178_REG_CF2_THR_RESET                  (0xffff)        /**< Default value of ADE9178_REG_CF2_THR */
#define ADE9178_REG_ZXTOUT_RESET                   (0xffff)        /**< Default value of ADE9178_REG_ZXTOUT */
#define ADE9178_REG_ZXTHRSH_RESET                  (0x19ea)        /**< Default value of ADE9178_REG_ZXTHRSH */
#define ADE9178_REG_ZX_LP_SEL_RESET                (0xf)           /**< Default value of ADE9178_REG_ZX_LP_SEL */
#define ADE9178_REG_SEQ_CYC_RESET                  (0x1)           /**< Default value of ADE9178_REG_SEQ_CYC */
#define ADE9178_REG_ACT_NL_LVL_RESET               (0xffff)        /**< Default value of ADE9178_REG_ACT_NL_LVL */
#define ADE9178_REG_APP_NL_LVL_RESET               (0xffff)        /**< Default value of ADE9178_REG_APP_NL_LVL */
#define ADE9178_REG_EP_CFG_RESET                   (0x0)           /**< Default value of ADE9178_REG_EP_CFG */
#define ADE9178_REG_EGY_TIME_RESET                 (0xff)          /**< Default value of ADE9178_REG_EGY_TIME */
#define ADE9178_REG_VSUMRMSONEOS_RESET             (0x0)           /**< Default value of ADE9178_REG_VSUMRMSONEOS */
#define ADE9178_REG_VSUMSWELLONE_LVL_RESET         (0xffffffff)    /**< Default value of ADE9178_REG_VSUMSWELLONE_LVL */
#define ADE9178_REG_VSUMSWELLONE_CYC_RESET         (0xffffffff)    /**< Default value of ADE9178_REG_VSUMSWELLONE_CYC */
#define ADE9178_REG_VABRMSONEOS_RESET              (0x0)           /**< Default value of ADE9178_REG_VABRMSONEOS */
#define ADE9178_REG_VABDIPONE_LVL_RESET            (0x0)           /**< Default value of ADE9178_REG_VABDIPONE_LVL */
#define ADE9178_REG_VABDIPONE_CYC_RESET            (0xffffffff)    /**< Default value of ADE9178_REG_VABDIPONE_CYC */
#define ADE9178_REG_VABSWELLONE_LVL_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_VABSWELLONE_LVL */
#define ADE9178_REG_VABSWELLONE_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_VABSWELLONE_CYC */
#define ADE9178_REG_VBCRMSONEOS_RESET              (0x0)           /**< Default value of ADE9178_REG_VBCRMSONEOS */
#define ADE9178_REG_VBCDIPONE_LVL_RESET            (0x0)           /**< Default value of ADE9178_REG_VBCDIPONE_LVL */
#define ADE9178_REG_VBCDIPONE_CYC_RESET            (0xffffffff)    /**< Default value of ADE9178_REG_VBCDIPONE_CYC */
#define ADE9178_REG_VBCSWELLONE_LVL_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_VBCSWELLONE_LVL */
#define ADE9178_REG_VBCSWELLONE_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_VBCSWELLONE_CYC */
#define ADE9178_REG_VACRMSONEOS_RESET              (0x0)           /**< Default value of ADE9178_REG_VACRMSONEOS */
#define ADE9178_REG_VACDIPONE_LVL_RESET            (0x0)           /**< Default value of ADE9178_REG_VACDIPONE_LVL */
#define ADE9178_REG_VACDIPONE_CYC_RESET            (0xffffffff)    /**< Default value of ADE9178_REG_VACDIPONE_CYC */
#define ADE9178_REG_VACSWELLONE_LVL_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_VACSWELLONE_LVL */
#define ADE9178_REG_VACSWELLONE_CYC_RESET          (0xffffffff)    /**< Default value of ADE9178_REG_VACSWELLONE_CYC */
#define ADE9178_REG_CF_LTMR_RESET                  (0x0)           /**< Default value of ADE9178_REG_CF_LTMR */
#define ADE9178_REG_WFS_CONFIG_RESET               (0xc)           /**< Default value of ADE9178_REG_WFS_CONFIG */
#define ADE9178_REG_ADC_CONTROL_RESET              (0x0)           /**< Default value of ADE9178_REG_ADC_CONTROL */
#define ADE9178_REG_ADC_CONFIG_RESET               (0x4)           /**< Default value of ADE9178_REG_ADC_CONFIG */
#define ADE9178_REG_ADC_REDIRECT0_RESET            (0x6431d2a)     /**< Default value of ADE9178_REG_ADC_REDIRECT0 */
#define ADE9178_REG_ADC_REDIRECT1_RESET            (0x410150b)     /**< Default value of ADE9178_REG_ADC_REDIRECT1 */
#define ADE9178_REG_CRC_OPTEN_RESET                (0x0)           /**< Default value of ADE9178_REG_CRC_OPTEN */
#define ADE9178_REG_CRC_FORCE_RESET                (0x0)           /**< Default value of ADE9178_REG_CRC_FORCE */
#define ADE9178_REG_CONFIG_LOCK_RESET              (0x0)           /**< Default value of ADE9178_REG_CONFIG_LOCK */
#define ADE9178_REG_AVRMS_RESET                    (0x0)           /**< Default value of ADE9178_REG_AVRMS */
#define ADE9178_REG_AVRMSHALF_RESET                (0x0)           /**< Default value of ADE9178_REG_AVRMSHALF */
#define ADE9178_REG_AVRMSONE_RESET                 (0x0)           /**< Default value of ADE9178_REG_AVRMSONE */
#define ADE9178_REG_AVDIPHALF_RESET                (0x7fffff)      /**< Default value of ADE9178_REG_AVDIPHALF */
#define ADE9178_REG_AVDIPONE_RESET                 (0x7fffff)      /**< Default value of ADE9178_REG_AVDIPONE */
#define ADE9178_REG_AVSWELLHALF_RESET              (0x0)           /**< Default value of ADE9178_REG_AVSWELLHALF */
#define ADE9178_REG_AVSWELLONE_RESET               (0x0)           /**< Default value of ADE9178_REG_AVSWELLONE */
#define ADE9178_REG_AIRMS_RESET                    (0x0)           /**< Default value of ADE9178_REG_AIRMS */
#define ADE9178_REG_AIRMSHALF_RESET                (0x0)           /**< Default value of ADE9178_REG_AIRMSHALF */
#define ADE9178_REG_AIRMSONE_RESET                 (0x0)           /**< Default value of ADE9178_REG_AIRMSONE */
#define ADE9178_REG_AIDIPHALF_RESET                (0x7fffff)      /**< Default value of ADE9178_REG_AIDIPHALF */
#define ADE9178_REG_AIDIPONE_RESET                 (0x7fffff)      /**< Default value of ADE9178_REG_AIDIPONE */
#define ADE9178_REG_AISWELLHALF_RESET              (0x0)           /**< Default value of ADE9178_REG_AISWELLHALF */
#define ADE9178_REG_AISWELLONE_RESET               (0x0)           /**< Default value of ADE9178_REG_AISWELLONE */
#define ADE9178_REG_BVRMS_RESET                    (0x0)           /**< Default value of ADE9178_REG_BVRMS */
#define ADE9178_REG_BVRMSHALF_RESET                (0x0)           /**< Default value of ADE9178_REG_BVRMSHALF */
#define ADE9178_REG_BVRMSONE_RESET                 (0x0)           /**< Default value of ADE9178_REG_BVRMSONE */
#define ADE9178_REG_BVDIPHALF_RESET                (0x7fffff)      /**< Default value of ADE9178_REG_BVDIPHALF */
#define ADE9178_REG_BVDIPONE_RESET                 (0x7fffff)      /**< Default value of ADE9178_REG_BVDIPONE */
#define ADE9178_REG_BVSWELLHALF_RESET              (0x0)           /**< Default value of ADE9178_REG_BVSWELLHALF */
#define ADE9178_REG_BVSWELLONE_RESET               (0x0)           /**< Default value of ADE9178_REG_BVSWELLONE */
#define ADE9178_REG_BIRMS_RESET                    (0x0)           /**< Default value of ADE9178_REG_BIRMS */
#define ADE9178_REG_BIRMSHALF_RESET                (0x0)           /**< Default value of ADE9178_REG_BIRMSHALF */
#define ADE9178_REG_BIRMSONE_RESET                 (0x0)           /**< Default value of ADE9178_REG_BIRMSONE */
#define ADE9178_REG_BIDIPHALF_RESET                (0x7fffff)      /**< Default value of ADE9178_REG_BIDIPHALF */
#define ADE9178_REG_BIDIPONE_RESET                 (0x7fffff)      /**< Default value of ADE9178_REG_BIDIPONE */
#define ADE9178_REG_BISWELLHALF_RESET              (0x0)           /**< Default value of ADE9178_REG_BISWELLHALF */
#define ADE9178_REG_BISWELLONE_RESET               (0x0)           /**< Default value of ADE9178_REG_BISWELLONE */
#define ADE9178_REG_CVRMS_RESET                    (0x0)           /**< Default value of ADE9178_REG_CVRMS */
#define ADE9178_REG_CVRMSHALF_RESET                (0x0)           /**< Default value of ADE9178_REG_CVRMSHALF */
#define ADE9178_REG_CVRMSONE_RESET                 (0x0)           /**< Default value of ADE9178_REG_CVRMSONE */
#define ADE9178_REG_CVDIPHALF_RESET                (0x7fffff)      /**< Default value of ADE9178_REG_CVDIPHALF */
#define ADE9178_REG_CVDIPONE_RESET                 (0x7fffff)      /**< Default value of ADE9178_REG_CVDIPONE */
#define ADE9178_REG_CVSWELLHALF_RESET              (0x0)           /**< Default value of ADE9178_REG_CVSWELLHALF */
#define ADE9178_REG_CVSWELLONE_RESET               (0x0)           /**< Default value of ADE9178_REG_CVSWELLONE */
#define ADE9178_REG_CIRMS_RESET                    (0x0)           /**< Default value of ADE9178_REG_CIRMS */
#define ADE9178_REG_CIRMSHALF_RESET                (0x0)           /**< Default value of ADE9178_REG_CIRMSHALF */
#define ADE9178_REG_CIRMSONE_RESET                 (0x0)           /**< Default value of ADE9178_REG_CIRMSONE */
#define ADE9178_REG_CIDIPHALF_RESET                (0x7fffff)      /**< Default value of ADE9178_REG_CIDIPHALF */
#define ADE9178_REG_CIDIPONE_RESET                 (0x7fffff)      /**< Default value of ADE9178_REG_CIDIPONE */
#define ADE9178_REG_CISWELLHALF_RESET              (0x0)           /**< Default value of ADE9178_REG_CISWELLHALF */
#define ADE9178_REG_CISWELLONE_RESET               (0x0)           /**< Default value of ADE9178_REG_CISWELLONE */
#define ADE9178_REG_AUX0RMS_RESET                  (0x0)           /**< Default value of ADE9178_REG_AUX0RMS */
#define ADE9178_REG_AUX0RMSHALF_RESET              (0x0)           /**< Default value of ADE9178_REG_AUX0RMSHALF */
#define ADE9178_REG_AUX0RMSONE_RESET               (0x0)           /**< Default value of ADE9178_REG_AUX0RMSONE */
#define ADE9178_REG_AUX0DIPHALF_RESET              (0x7fffff)      /**< Default value of ADE9178_REG_AUX0DIPHALF */
#define ADE9178_REG_AUX0DIPONE_RESET               (0x7fffff)      /**< Default value of ADE9178_REG_AUX0DIPONE */
#define ADE9178_REG_AUX0SWELLHALF_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX0SWELLHALF */
#define ADE9178_REG_AUX0SWELLONE_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX0SWELLONE */
#define ADE9178_REG_AUX1RMS_RESET                  (0x0)           /**< Default value of ADE9178_REG_AUX1RMS */
#define ADE9178_REG_AUX1RMSHALF_RESET              (0x0)           /**< Default value of ADE9178_REG_AUX1RMSHALF */
#define ADE9178_REG_AUX1RMSONE_RESET               (0x0)           /**< Default value of ADE9178_REG_AUX1RMSONE */
#define ADE9178_REG_AUX1DIPHALF_RESET              (0x7fffff)      /**< Default value of ADE9178_REG_AUX1DIPHALF */
#define ADE9178_REG_AUX1DIPONE_RESET               (0x7fffff)      /**< Default value of ADE9178_REG_AUX1DIPONE */
#define ADE9178_REG_AUX1SWELLHALF_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX1SWELLHALF */
#define ADE9178_REG_AUX1SWELLONE_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX1SWELLONE */
#define ADE9178_REG_AUX2RMS_RESET                  (0x0)           /**< Default value of ADE9178_REG_AUX2RMS */
#define ADE9178_REG_AUX2RMSHALF_RESET              (0x0)           /**< Default value of ADE9178_REG_AUX2RMSHALF */
#define ADE9178_REG_AUX2RMSONE_RESET               (0x0)           /**< Default value of ADE9178_REG_AUX2RMSONE */
#define ADE9178_REG_AUX2DIPHALF_RESET              (0x7fffff)      /**< Default value of ADE9178_REG_AUX2DIPHALF */
#define ADE9178_REG_AUX2DIPONE_RESET               (0x7fffff)      /**< Default value of ADE9178_REG_AUX2DIPONE */
#define ADE9178_REG_AUX2SWELLHALF_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX2SWELLHALF */
#define ADE9178_REG_AUX2SWELLONE_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX2SWELLONE */
#define ADE9178_REG_AUX3RMS_RESET                  (0x0)           /**< Default value of ADE9178_REG_AUX3RMS */
#define ADE9178_REG_AUX3RMSHALF_RESET              (0x0)           /**< Default value of ADE9178_REG_AUX3RMSHALF */
#define ADE9178_REG_AUX3RMSONE_RESET               (0x0)           /**< Default value of ADE9178_REG_AUX3RMSONE */
#define ADE9178_REG_AUX3DIPHALF_RESET              (0x7fffff)      /**< Default value of ADE9178_REG_AUX3DIPHALF */
#define ADE9178_REG_AUX3DIPONE_RESET               (0x7fffff)      /**< Default value of ADE9178_REG_AUX3DIPONE */
#define ADE9178_REG_AUX3SWELLHALF_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX3SWELLHALF */
#define ADE9178_REG_AUX3SWELLONE_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX3SWELLONE */
#define ADE9178_REG_AUX4RMS_RESET                  (0x0)           /**< Default value of ADE9178_REG_AUX4RMS */
#define ADE9178_REG_AUX4RMSHALF_RESET              (0x0)           /**< Default value of ADE9178_REG_AUX4RMSHALF */
#define ADE9178_REG_AUX4RMSONE_RESET               (0x0)           /**< Default value of ADE9178_REG_AUX4RMSONE */
#define ADE9178_REG_AUX4DIPHALF_RESET              (0x7fffff)      /**< Default value of ADE9178_REG_AUX4DIPHALF */
#define ADE9178_REG_AUX4DIPONE_RESET               (0x7fffff)      /**< Default value of ADE9178_REG_AUX4DIPONE */
#define ADE9178_REG_AUX4SWELLHALF_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX4SWELLHALF */
#define ADE9178_REG_AUX4SWELLONE_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX4SWELLONE */
#define ADE9178_REG_AUX5RMS_RESET                  (0x0)           /**< Default value of ADE9178_REG_AUX5RMS */
#define ADE9178_REG_AUX5RMSHALF_RESET              (0x0)           /**< Default value of ADE9178_REG_AUX5RMSHALF */
#define ADE9178_REG_AUX5RMSONE_RESET               (0x0)           /**< Default value of ADE9178_REG_AUX5RMSONE */
#define ADE9178_REG_AUX5DIPHALF_RESET              (0x7fffff)      /**< Default value of ADE9178_REG_AUX5DIPHALF */
#define ADE9178_REG_AUX5DIPONE_RESET               (0x7fffff)      /**< Default value of ADE9178_REG_AUX5DIPONE */
#define ADE9178_REG_AUX5SWELLHALF_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX5SWELLHALF */
#define ADE9178_REG_AUX5SWELLONE_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX5SWELLONE */
#define ADE9178_REG_AWATT_RESET                    (0x0)           /**< Default value of ADE9178_REG_AWATT */
#define ADE9178_REG_AVA_RESET                      (0x0)           /**< Default value of ADE9178_REG_AVA */
#define ADE9178_REG_APF_RESET                      (0x0)           /**< Default value of ADE9178_REG_APF */
#define ADE9178_REG_AWATTHR_POS_LO_RESET           (0x0)           /**< Default value of ADE9178_REG_AWATTHR_POS_LO */
#define ADE9178_REG_AWATTHR_POS_HI_RESET           (0x0)           /**< Default value of ADE9178_REG_AWATTHR_POS_HI */
#define ADE9178_REG_AWATTHR_NEG_LO_RESET           (0x0)           /**< Default value of ADE9178_REG_AWATTHR_NEG_LO */
#define ADE9178_REG_AWATTHR_NEG_HI_RESET           (0x0)           /**< Default value of ADE9178_REG_AWATTHR_NEG_HI */
#define ADE9178_REG_AWATTHR_SIGNED_LO_RESET        (0x0)           /**< Default value of ADE9178_REG_AWATTHR_SIGNED_LO */
#define ADE9178_REG_AWATTHR_SIGNED_HI_RESET        (0x0)           /**< Default value of ADE9178_REG_AWATTHR_SIGNED_HI */
#define ADE9178_REG_AVAHR_LO_RESET                 (0x0)           /**< Default value of ADE9178_REG_AVAHR_LO */
#define ADE9178_REG_AVAHR_HI_RESET                 (0x0)           /**< Default value of ADE9178_REG_AVAHR_HI */
#define ADE9178_REG_BWATT_RESET                    (0x0)           /**< Default value of ADE9178_REG_BWATT */
#define ADE9178_REG_BVA_RESET                      (0x0)           /**< Default value of ADE9178_REG_BVA */
#define ADE9178_REG_BPF_RESET                      (0x0)           /**< Default value of ADE9178_REG_BPF */
#define ADE9178_REG_BWATTHR_POS_LO_RESET           (0x0)           /**< Default value of ADE9178_REG_BWATTHR_POS_LO */
#define ADE9178_REG_BWATTHR_POS_HI_RESET           (0x0)           /**< Default value of ADE9178_REG_BWATTHR_POS_HI */
#define ADE9178_REG_BWATTHR_NEG_LO_RESET           (0x0)           /**< Default value of ADE9178_REG_BWATTHR_NEG_LO */
#define ADE9178_REG_BWATTHR_NEG_HI_RESET           (0x0)           /**< Default value of ADE9178_REG_BWATTHR_NEG_HI */
#define ADE9178_REG_BWATTHR_SIGNED_LO_RESET        (0x0)           /**< Default value of ADE9178_REG_BWATTHR_SIGNED_LO */
#define ADE9178_REG_BWATTHR_SIGNED_HI_RESET        (0x0)           /**< Default value of ADE9178_REG_BWATTHR_SIGNED_HI */
#define ADE9178_REG_BVAHR_LO_RESET                 (0x0)           /**< Default value of ADE9178_REG_BVAHR_LO */
#define ADE9178_REG_BVAHR_HI_RESET                 (0x0)           /**< Default value of ADE9178_REG_BVAHR_HI */
#define ADE9178_REG_CWATT_RESET                    (0x0)           /**< Default value of ADE9178_REG_CWATT */
#define ADE9178_REG_CVA_RESET                      (0x0)           /**< Default value of ADE9178_REG_CVA */
#define ADE9178_REG_CPF_RESET                      (0x0)           /**< Default value of ADE9178_REG_CPF */
#define ADE9178_REG_CWATTHR_POS_LO_RESET           (0x0)           /**< Default value of ADE9178_REG_CWATTHR_POS_LO */
#define ADE9178_REG_CWATTHR_POS_HI_RESET           (0x0)           /**< Default value of ADE9178_REG_CWATTHR_POS_HI */
#define ADE9178_REG_CWATTHR_NEG_LO_RESET           (0x0)           /**< Default value of ADE9178_REG_CWATTHR_NEG_LO */
#define ADE9178_REG_CWATTHR_NEG_HI_RESET           (0x0)           /**< Default value of ADE9178_REG_CWATTHR_NEG_HI */
#define ADE9178_REG_CWATTHR_SIGNED_LO_RESET        (0x0)           /**< Default value of ADE9178_REG_CWATTHR_SIGNED_LO */
#define ADE9178_REG_CWATTHR_SIGNED_HI_RESET        (0x0)           /**< Default value of ADE9178_REG_CWATTHR_SIGNED_HI */
#define ADE9178_REG_CVAHR_LO_RESET                 (0x0)           /**< Default value of ADE9178_REG_CVAHR_LO */
#define ADE9178_REG_CVAHR_HI_RESET                 (0x0)           /**< Default value of ADE9178_REG_CVAHR_HI */
#define ADE9178_REG_ANGL_AV_BV_RESET               (0x0)           /**< Default value of ADE9178_REG_ANGL_AV_BV */
#define ADE9178_REG_ANGL_BV_CV_RESET               (0x0)           /**< Default value of ADE9178_REG_ANGL_BV_CV */
#define ADE9178_REG_ANGL_AV_CV_RESET               (0x0)           /**< Default value of ADE9178_REG_ANGL_AV_CV */
#define ADE9178_REG_ANGL_AV_AI_RESET               (0x0)           /**< Default value of ADE9178_REG_ANGL_AV_AI */
#define ADE9178_REG_ANGL_BV_BI_RESET               (0x0)           /**< Default value of ADE9178_REG_ANGL_BV_BI */
#define ADE9178_REG_ANGL_CV_CI_RESET               (0x0)           /**< Default value of ADE9178_REG_ANGL_CV_CI */
#define ADE9178_REG_ANGL_AI_BI_RESET               (0x0)           /**< Default value of ADE9178_REG_ANGL_AI_BI */
#define ADE9178_REG_ANGL_BI_CI_RESET               (0x0)           /**< Default value of ADE9178_REG_ANGL_BI_CI */
#define ADE9178_REG_ANGL_AI_CI_RESET               (0x0)           /**< Default value of ADE9178_REG_ANGL_AI_CI */
#define ADE9178_REG_ISUMRMS_RESET                  (0x0)           /**< Default value of ADE9178_REG_ISUMRMS */
#define ADE9178_REG_PEN_PERIOD_RESET               (0x500000)      /**< Default value of ADE9178_REG_PEN_PERIOD */
#define ADE9178_REG_APERIOD_RESET                  (0x500000)      /**< Default value of ADE9178_REG_APERIOD */
#define ADE9178_REG_BPERIOD_RESET                  (0x500000)      /**< Default value of ADE9178_REG_BPERIOD */
#define ADE9178_REG_CPERIOD_RESET                  (0x500000)      /**< Default value of ADE9178_REG_CPERIOD */
#define ADE9178_REG_COM_PERIOD_RESET               (0x500000)      /**< Default value of ADE9178_REG_COM_PERIOD */
#define ADE9178_REG_IPEAK_RESET                    (0x0)           /**< Default value of ADE9178_REG_IPEAK */
#define ADE9178_REG_VPEAK_RESET                    (0x0)           /**< Default value of ADE9178_REG_VPEAK */
#define ADE9178_REG_AUXPEAK_RESET                  (0x0)           /**< Default value of ADE9178_REG_AUXPEAK */
#define ADE9178_REG_PHSIGN_RESET                   (0x0)           /**< Default value of ADE9178_REG_PHSIGN */
#define ADE9178_REG_PHNOLOAD_RESET                 (0x0)           /**< Default value of ADE9178_REG_PHNOLOAD */
#define ADE9178_REG_VSUMRMSONE_RESET               (0x0)           /**< Default value of ADE9178_REG_VSUMRMSONE */
#define ADE9178_REG_VSUMSWELLONE_RESET             (0x7fffff)      /**< Default value of ADE9178_REG_VSUMSWELLONE */
#define ADE9178_REG_VABRMSONE_RESET                (0x0)           /**< Default value of ADE9178_REG_VABRMSONE */
#define ADE9178_REG_VABDIPONE_RESET                (0x7fffff)      /**< Default value of ADE9178_REG_VABDIPONE */
#define ADE9178_REG_VABSWELLONE_RESET              (0x7fffff)      /**< Default value of ADE9178_REG_VABSWELLONE */
#define ADE9178_REG_VBCRMSONE_RESET                (0x0)           /**< Default value of ADE9178_REG_VBCRMSONE */
#define ADE9178_REG_VBCDIPONE_RESET                (0x7fffff)      /**< Default value of ADE9178_REG_VBCDIPONE */
#define ADE9178_REG_VBCSWELLONE_RESET              (0x7fffff)      /**< Default value of ADE9178_REG_VBCSWELLONE */
#define ADE9178_REG_VACRMSONE_RESET                (0x0)           /**< Default value of ADE9178_REG_VACRMSONE */
#define ADE9178_REG_VACDIPONE_RESET                (0x7fffff)      /**< Default value of ADE9178_REG_VACDIPONE */
#define ADE9178_REG_VACSWELLONE_RESET              (0x7fffff)      /**< Default value of ADE9178_REG_VACSWELLONE */
#define ADE9178_REG_CRC_RSLT_RESET                 (0x0)           /**< Default value of ADE9178_REG_CRC_RSLT */
#define ADE9178_REG_STATUS0_RESET                  (0x0)           /**< Default value of ADE9178_REG_STATUS0 */
#define ADE9178_REG_STATUS1_RESET                  (0x0)           /**< Default value of ADE9178_REG_STATUS1 */
#define ADE9178_REG_STATUS2_RESET                  (0x0)           /**< Default value of ADE9178_REG_STATUS2 */
#define ADE9178_REG_STATUS3_RESET                  (0x0)           /**< Default value of ADE9178_REG_STATUS3 */
#define ADE9178_REG_ERROR_STATUS_RESET             (0x0)           /**< Default value of ADE9178_REG_ERROR_STATUS */
#define ADE9178_REG_MASK0_RESET                    (0x4000)        /**< Default value of ADE9178_REG_MASK0 */
#define ADE9178_REG_MASK1_RESET                    (0x4000)        /**< Default value of ADE9178_REG_MASK1 */
#define ADE9178_REG_MASK2_RESET                    (0x0)           /**< Default value of ADE9178_REG_MASK2 */
#define ADE9178_REG_MASK3_RESET                    (0x0)           /**< Default value of ADE9178_REG_MASK3 */
#define ADE9178_REG_ERROR_MASK_RESET               (0x7fffff)      /**< Default value of ADE9178_REG_ERROR_MASK */
#define ADE9178_REG_VERSION_RESET                  (0x1000000)     /**< Default value of ADE9178_REG_VERSION */
#define ADE9178_REG_VERSION2_RESET                 (0x9fd5d0d)     /**< Default value of ADE9178_REG_VERSION2 */
#define ADE9178_REG_AVRMS_1_RESET                  (0x0)           /**< Default value of ADE9178_REG_AVRMS_1 */
#define ADE9178_REG_BVRMS_1_RESET                  (0x0)           /**< Default value of ADE9178_REG_BVRMS_1 */
#define ADE9178_REG_CVRMS_1_RESET                  (0x0)           /**< Default value of ADE9178_REG_CVRMS_1 */
#define ADE9178_REG_AIRMS_1_RESET                  (0x0)           /**< Default value of ADE9178_REG_AIRMS_1 */
#define ADE9178_REG_BIRMS_1_RESET                  (0x0)           /**< Default value of ADE9178_REG_BIRMS_1 */
#define ADE9178_REG_CIRMS_1_RESET                  (0x0)           /**< Default value of ADE9178_REG_CIRMS_1 */
#define ADE9178_REG_AUX0RMS_1_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX0RMS_1 */
#define ADE9178_REG_AUX1RMS_1_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX1RMS_1 */
#define ADE9178_REG_AUX2RMS_1_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX2RMS_1 */
#define ADE9178_REG_AUX3RMS_1_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX3RMS_1 */
#define ADE9178_REG_AUX4RMS_1_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX4RMS_1 */
#define ADE9178_REG_AUX5RMS_1_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX5RMS_1 */
#define ADE9178_REG_AWATT_1_RESET                  (0x0)           /**< Default value of ADE9178_REG_AWATT_1 */
#define ADE9178_REG_BWATT_1_RESET                  (0x0)           /**< Default value of ADE9178_REG_BWATT_1 */
#define ADE9178_REG_CWATT_1_RESET                  (0x0)           /**< Default value of ADE9178_REG_CWATT_1 */
#define ADE9178_REG_AVA_1_RESET                    (0x0)           /**< Default value of ADE9178_REG_AVA_1 */
#define ADE9178_REG_BVA_1_RESET                    (0x0)           /**< Default value of ADE9178_REG_BVA_1 */
#define ADE9178_REG_CVA_1_RESET                    (0x0)           /**< Default value of ADE9178_REG_CVA_1 */
#define ADE9178_REG_APF_1_RESET                    (0x0)           /**< Default value of ADE9178_REG_APF_1 */
#define ADE9178_REG_BPF_1_RESET                    (0x0)           /**< Default value of ADE9178_REG_BPF_1 */
#define ADE9178_REG_CPF_1_RESET                    (0x0)           /**< Default value of ADE9178_REG_CPF_1 */
#define ADE9178_REG_AVRMSONE_1_RESET               (0x0)           /**< Default value of ADE9178_REG_AVRMSONE_1 */
#define ADE9178_REG_BVRMSONE_1_RESET               (0x0)           /**< Default value of ADE9178_REG_BVRMSONE_1 */
#define ADE9178_REG_CVRMSONE_1_RESET               (0x0)           /**< Default value of ADE9178_REG_CVRMSONE_1 */
#define ADE9178_REG_AIRMSONE_1_RESET               (0x0)           /**< Default value of ADE9178_REG_AIRMSONE_1 */
#define ADE9178_REG_BIRMSONE_1_RESET               (0x0)           /**< Default value of ADE9178_REG_BIRMSONE_1 */
#define ADE9178_REG_CIRMSONE_1_RESET               (0x0)           /**< Default value of ADE9178_REG_CIRMSONE_1 */
#define ADE9178_REG_AUX0RMSONE_1_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX0RMSONE_1 */
#define ADE9178_REG_AUX1RMSONE_1_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX1RMSONE_1 */
#define ADE9178_REG_AUX2RMSONE_1_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX2RMSONE_1 */
#define ADE9178_REG_AUX3RMSONE_1_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX3RMSONE_1 */
#define ADE9178_REG_AUX4RMSONE_1_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX4RMSONE_1 */
#define ADE9178_REG_AUX5RMSONE_1_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX5RMSONE_1 */
#define ADE9178_REG_VSUMRMSONE_1_RESET             (0x0)           /**< Default value of ADE9178_REG_VSUMRMSONE_1 */
#define ADE9178_REG_VABRMSONE_1_RESET              (0x0)           /**< Default value of ADE9178_REG_VABRMSONE_1 */
#define ADE9178_REG_VBCRMSONE_1_RESET              (0x0)           /**< Default value of ADE9178_REG_VBCRMSONE_1 */
#define ADE9178_REG_VACRMSONE_1_RESET              (0x0)           /**< Default value of ADE9178_REG_VACRMSONE_1 */
#define ADE9178_REG_AVRMSHALF_1_RESET              (0x0)           /**< Default value of ADE9178_REG_AVRMSHALF_1 */
#define ADE9178_REG_BVRMSHALF_1_RESET              (0x0)           /**< Default value of ADE9178_REG_BVRMSHALF_1 */
#define ADE9178_REG_CVRMSHALF_1_RESET              (0x0)           /**< Default value of ADE9178_REG_CVRMSHALF_1 */
#define ADE9178_REG_AIRMSHALF_1_RESET              (0x0)           /**< Default value of ADE9178_REG_AIRMSHALF_1 */
#define ADE9178_REG_BIRMSHALF_1_RESET              (0x0)           /**< Default value of ADE9178_REG_BIRMSHALF_1 */
#define ADE9178_REG_CIRMSHALF_1_RESET              (0x0)           /**< Default value of ADE9178_REG_CIRMSHALF_1 */
#define ADE9178_REG_AUX0RMSHALF_1_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX0RMSHALF_1 */
#define ADE9178_REG_AUX1RMSHALF_1_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX1RMSHALF_1 */
#define ADE9178_REG_AUX2RMSHALF_1_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX2RMSHALF_1 */
#define ADE9178_REG_AUX3RMSHALF_1_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX3RMSHALF_1 */
#define ADE9178_REG_AUX4RMSHALF_1_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX4RMSHALF_1 */
#define ADE9178_REG_AUX5RMSHALF_1_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX5RMSHALF_1 */
#define ADE9178_REG_AVRMS_2_RESET                  (0x0)           /**< Default value of ADE9178_REG_AVRMS_2 */
#define ADE9178_REG_AIRMS_2_RESET                  (0x0)           /**< Default value of ADE9178_REG_AIRMS_2 */
#define ADE9178_REG_AWATT_2_RESET                  (0x0)           /**< Default value of ADE9178_REG_AWATT_2 */
#define ADE9178_REG_AVA_2_RESET                    (0x0)           /**< Default value of ADE9178_REG_AVA_2 */
#define ADE9178_REG_APF_2_RESET                    (0x0)           /**< Default value of ADE9178_REG_APF_2 */
#define ADE9178_REG_AVRMSONE_2_RESET               (0x0)           /**< Default value of ADE9178_REG_AVRMSONE_2 */
#define ADE9178_REG_AIRMSONE_2_RESET               (0x0)           /**< Default value of ADE9178_REG_AIRMSONE_2 */
#define ADE9178_REG_AVRMSHALF_2_RESET              (0x0)           /**< Default value of ADE9178_REG_AVRMSHALF_2 */
#define ADE9178_REG_AIRMSHALF_2_RESET              (0x0)           /**< Default value of ADE9178_REG_AIRMSHALF_2 */
#define ADE9178_REG_BVRMS_2_RESET                  (0x0)           /**< Default value of ADE9178_REG_BVRMS_2 */
#define ADE9178_REG_BIRMS_2_RESET                  (0x0)           /**< Default value of ADE9178_REG_BIRMS_2 */
#define ADE9178_REG_BWATT_2_RESET                  (0x0)           /**< Default value of ADE9178_REG_BWATT_2 */
#define ADE9178_REG_BVA_2_RESET                    (0x0)           /**< Default value of ADE9178_REG_BVA_2 */
#define ADE9178_REG_BPF_2_RESET                    (0x0)           /**< Default value of ADE9178_REG_BPF_2 */
#define ADE9178_REG_BVRMSONE_2_RESET               (0x0)           /**< Default value of ADE9178_REG_BVRMSONE_2 */
#define ADE9178_REG_BIRMSONE_2_RESET               (0x0)           /**< Default value of ADE9178_REG_BIRMSONE_2 */
#define ADE9178_REG_BVRMSHALF_2_RESET              (0x0)           /**< Default value of ADE9178_REG_BVRMSHALF_2 */
#define ADE9178_REG_BIRMSHALF_2_RESET              (0x0)           /**< Default value of ADE9178_REG_BIRMSHALF_2 */
#define ADE9178_REG_CVRMS_2_RESET                  (0x0)           /**< Default value of ADE9178_REG_CVRMS_2 */
#define ADE9178_REG_CIRMS_2_RESET                  (0x0)           /**< Default value of ADE9178_REG_CIRMS_2 */
#define ADE9178_REG_CWATT_2_RESET                  (0x0)           /**< Default value of ADE9178_REG_CWATT_2 */
#define ADE9178_REG_CVA_2_RESET                    (0x0)           /**< Default value of ADE9178_REG_CVA_2 */
#define ADE9178_REG_CPF_2_RESET                    (0x0)           /**< Default value of ADE9178_REG_CPF_2 */
#define ADE9178_REG_CVRMSONE_2_RESET               (0x0)           /**< Default value of ADE9178_REG_CVRMSONE_2 */
#define ADE9178_REG_CIRMSONE_2_RESET               (0x0)           /**< Default value of ADE9178_REG_CIRMSONE_2 */
#define ADE9178_REG_CVRMSHALF_2_RESET              (0x0)           /**< Default value of ADE9178_REG_CVRMSHALF_2 */
#define ADE9178_REG_CIRMSHALF_2_RESET              (0x0)           /**< Default value of ADE9178_REG_CIRMSHALF_2 */
#define ADE9178_REG_AUX0RMS_2_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX0RMS_2 */
#define ADE9178_REG_AUX0RMSONE_2_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX0RMSONE_2 */
#define ADE9178_REG_AUX0RMSHALF_2_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX0RMSHALF_2 */
#define ADE9178_REG_AUX1RMS_2_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX1RMS_2 */
#define ADE9178_REG_AUX1RMSONE_2_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX1RMSONE_2 */
#define ADE9178_REG_AUX1RMSHALF_2_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX1RMSHALF_2 */
#define ADE9178_REG_AUX2RMS_2_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX2RMS_2 */
#define ADE9178_REG_AUX2RMSONE_2_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX2RMSONE_2 */
#define ADE9178_REG_AUX2RMSHALF_2_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX2RMSHALF_2 */
#define ADE9178_REG_AUX3RMS_2_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX3RMS_2 */
#define ADE9178_REG_AUX3RMSONE_2_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX3RMSONE_2 */
#define ADE9178_REG_AUX3RMSHALF_2_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX3RMSHALF_2 */
#define ADE9178_REG_AUX4RMS_2_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX4RMS_2 */
#define ADE9178_REG_AUX4RMSONE_2_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX4RMSONE_2 */
#define ADE9178_REG_AUX4RMSHALF_2_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX4RMSHALF_2 */
#define ADE9178_REG_AUX5RMS_2_RESET                (0x0)           /**< Default value of ADE9178_REG_AUX5RMS_2 */
#define ADE9178_REG_AUX5RMSONE_2_RESET             (0x0)           /**< Default value of ADE9178_REG_AUX5RMSONE_2 */
#define ADE9178_REG_AUX5RMSHALF_2_RESET            (0x0)           /**< Default value of ADE9178_REG_AUX5RMSHALF_2 */
#define ADE9178_REG_VSUMRMSONE_2_RESET             (0x0)           /**< Default value of ADE9178_REG_VSUMRMSONE_2 */
#define ADE9178_REG_VABRMSONE_2_RESET              (0x0)           /**< Default value of ADE9178_REG_VABRMSONE_2 */
#define ADE9178_REG_VBCRMSONE_2_RESET              (0x0)           /**< Default value of ADE9178_REG_VBCRMSONE_2 */
#define ADE9178_REG_VACRMSONE_2_RESET              (0x0)           /**< Default value of ADE9178_REG_VACRMSONE_2 */
#endif /* __ADE9178_DEFAULT_H__*/

/**
 * @}
 */
